'use client'
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Sidebar from "./components/Sidebar";
import { useState } from "react";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  // const [toggleValue, setToggleValue] = useState(false)
  // const handleToggleValue = (toggle) => {
  //   setToggleValue(toggle)
  // }
  return (
    <html lang="en">
      <body className={inter.className}>
        
          {children}
      </body>
    </html>
  );
}
